project:
  type: website

website:
  title: "Tim's Blog"
  site-url: "https://www.tbeck.io"
  page-footer: "© Tim Beck, 2022. All Rights Reserved.<br>Powered by <a href=\"https://www.quarto.org\">Quarto</a>"
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: posts/
      - icon: github
        href: https://github.com/tmbeck
      - icon: linkedin
        href: https://linkedin.com/in/tmbeck
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
