project:
  type: website
  output-dir: ../_site

website:
  title: "Tim's Blog"
  site-url: "https://www.tbeck.io/blog"
  page-footer: "© Tim Beck, 2022. All Rights Reserved."
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: posts/
      - icon: github
        href: https://github.com/tmbeck
      - icon: linkedin
        href: https://linkedin.com/in/tmbeck
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
